Repository StanfordBDHG/LLMonFHIR, pull requests merged in 2025-03, with the labels that each got.

#70 Enhance Likert Scale Response Option Labels
  LLMonFHIR/FHIRInterpretation/MultipleResources/UserStudy/Survey.swift
  LLMonFHIR/FHIRInterpretation/MultipleResources/UserStudy/SurveyView.swift
  LLMonFHIR/FHIRInterpretation/MultipleResources/UserStudy/UserStudyWelcomeView.swift
Labels: enhancement

#72 Incorporate Clinical Document References Such as Discharge Reports, Clinical Notes, and More
  .github/workflows/user-study-beta-deployment.yml
  LLMonFHIR.xcodeproj/project.pbxproj
  LLMonFHIR.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  LLMonFHIR.xcodeproj/xcshareddata/xcschemes/LLMonFHIR.xcscheme
  LLMonFHIR/FHIR Views/FHIRResourcesView.swift
  LLMonFHIR/FHIRInterpretation/MultipleResources/FHIRGetResourceLLMFunction.swift
  LLMonFHIR/FHIRInterpretation/MultipleResources/FHIRMultipleResourceInterpreter.swift
  LLMonFHIR/FHIRInterpretation/MultipleResources/MultipleResourcesChatView.swift
  LLMonFHIR/FHIRInterpretation/MultipleResources/UserStudy/SurveyView.swift
  LLMonFHIR/FHIRInterpretationModule.swift
  LLMonFHIR/FHIRSummary/FHIRResourceSummary.swift
  LLMonFHIR/Helper/FHIRStore+Interpretation.swift
  LLMonFHIR/LLMonFHIRStandard.swift
  LLMonFHIR/ResourceView.swift
  LLMonFHIR/Resources/Localizable.xcstrings
  LLMonFHIR/Settings/ResourceSelection.swift
  LLMonFHIR/Settings/SettingsView.swift
  LLMonFHIR/SharedContext/FeatureFlags.swift
  LLMonFHIR/SharedContext/StorageKeys.swift
Labels: enhancement

#78 Simplify Logic & Improve Resource Selection
  .reuse/dep5
  LLMonFHIR.xcodeproj/project.pbxproj
  LLMonFHIR/FHIR Views/FHIRResourcesView.swift
  LLMonFHIR/FHIR Views/InspectResourceChat.swift
  LLMonFHIR/FHIR Views/InspectResourceView.swift
  LLMonFHIR/FHIRInterpretation/MultipleResources/FHIRGetResourceLLMFunction.swift
  LLMonFHIR/FHIRInterpretation/MultipleResources/FHIRMultipleResourceInterpreter.swift
  LLMonFHIR/FHIRInterpretation/MultipleResources/MultipleResourcesChatView.swift
  LLMonFHIR/FHIRInterpretation/MultipleResources/UserStudy/UserStudyFHIRMultipleResourceInterpreter.swift
  LLMonFHIR/FHIRInterpretation/UserStudy/Survey.swift
  LLMonFHIR/FHIRInterpretation/UserStudy/SurveyView.swift
  LLMonFHIR/FHIRInterpretation/UserStudy/UserStudyChatView.swift
  LLMonFHIR/FHIRInterpretation/UserStudy/UserStudyPlistConfiguration.swift
  LLMonFHIR/FHIRInterpretation/UserStudy/UserStudyWelcomeView.swift
  LLMonFHIR/FHIRInterpretationModule.swift
  LLMonFHIR/Helper/FHIRResource+Identifier.swift
  LLMonFHIR/Helper/FHIRStore+Interpretation.swift
  LLMonFHIR/Home.swift
  LLMonFHIR/LLMonFHIRStandard.swift
  LLMonFHIR/Resources/AppIcon.png.license
  LLMonFHIR/Resources/Assets.xcassets/AccentColor.colorset/Contents.json.license
  LLMonFHIR/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon.png.license
  LLMonFHIR/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json.license
  LLMonFHIR/Resources/Assets.xcassets/Contents.json.license
  LLMonFHIR/Resources/Assets.xcassets/StanfordBlockSTree.imageset/Block_S_2_color.png.license
  LLMonFHIR/Resources/Assets.xcassets/StanfordBlockSTree.imageset/Contents.json.license
  LLMonFHIR/Resources/Localizable.xcstrings
  LLMonFHIR/Settings/OpenAIModelParametersView.swift
  LLMonFHIR/Settings/ResourceSelection.swift
  LLMonFHIR/Settings/SettingsView.swift
  LLMonFHIR/SharedContext/StorageKeys.swift
Labels: enhancement

#81 Collapse Resource Categories by Default
  LLMonFHIR/FHIR Views/FHIRResourcesView.swift
  LLMonFHIR/Resources/Localizable.xcstrings
Labels: enhancement

#82 🚀 Small Improvements
  LLMonFHIR/FHIRInterpretation/MultipleResources/FHIRGetResourceLLMFunction.swift
  LLMonFHIR/Resources/Localizable.xcstrings
  LLMonFHIR/Settings/OpenAIModelParametersView.swift
  LLMonFHIR/Settings/SettingsView.swift
Labels: enhancement

#80 Improve Parsing Logic for Resource Summary
  LLMonFHIR/FHIRSummary/FHIRResourceSummary.swift
  LLMonFHIR/LLMonFHIRDelegate.swift
  LLMonFHIRTests/FHIRSummary/FHIRResourceSummaryTests.swift
Labels: enhancement

#83 Update Dependencies
  LLMonFHIR.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  LLMonFHIR/FHIRInterpretation/MultipleResources/FHIRGetResourceLLMFunction.swift
  LLMonFHIR/FHIRInterpretation/MultipleResources/FHIRMultipleResourceInterpreter.swift
  LLMonFHIR/Resources/Localizable.xcstrings
Labels: dependencies

#86 Refactor FHIR Multiple Resource Interpreter and Chat
  LLMonFHIR.xcodeproj/project.pbxproj
  LLMonFHIR.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  LLMonFHIR/FHIRInterpretation/MultipleResources/FHIRMultipleResourceInterpreter.swift
  LLMonFHIR/FHIRInterpretation/MultipleResources/MultipleResourceChatViewModel.swift
  LLMonFHIR/FHIRInterpretation/MultipleResources/MultipleResourcesChatView.swift
  LLMonFHIR/FHIRInterpretation/UserStudy/UserStudyChatToolbar.swift
  LLMonFHIR/FHIRInterpretation/UserStudy/UserStudyChatView.swift
  LLMonFHIR/FHIRInterpretation/UserStudy/UserStudyChatViewModel.swift
  LLMonFHIR/FHIRInterpretation/UserStudy/UserStudyWelcomeView.swift
  LLMonFHIR/FHIRInterpretationModule.swift
  LLMonFHIR/Home.swift
  LLMonFHIR/Settings/ResourceSelection.swift
Labels: enhancement

#87 Update Task 4 in Survey Questionnaire
  LLMonFHIR/FHIRInterpretation/UserStudy/UserStudyWelcomeView.swift
Labels: bug
